### ISSUE TITLE
Why does `wrap: false` disable the domain-specific language?

### ISSUE THREAD

**Issue by sbj42** [yargs/cliui#51]
Setting `wrap` to false disables the domain-specific language.  I see this is intentional as indicated in the test case ("does not apply DSL if wrap is false") and the code (`index.js:26`).  But I don't understand the reason.

If I enable the DSL for `wrap: false` by removing the condition on line 26, the only test that fails is the one that confirms the DSL is disabled.  The new output of that test is "Usage : $0twothree" which is actually what I would expect given my understanding of the documentation for `wrap: false`: "disable the wrapping of text in a column".

I would think that the `wrap` option would have no effect when the input doesn't need wrapping.

Seems like it should keep the DSL enabled when `wrap` is false.  You could add a new option specifically to disable the DSL if there is a use case for that.  Alternatively, you could mention the DSL thing in the `wrap` documentation.

**Comment by bcoe** [comment]
@sbj42 I apologize for ignoring this for so long; unfortunately the utility libraries I work on tend to not be updated as frequently as the main libraries like yargs.

Is this still a feature you'd like? perhaps we can discuss landing here:

http://devtoolscommunity.herokuapp.com/

**Comment by sbj42** [comment]
No problem.  The project I was working on that used `cliui` is on hold at the moment, so there is no urgency to this issue.  I'll let you know if that changes.
