### ISSUE TITLE
Difficult to tightly pack columns

### ISSUE THREAD

**Issue by sbj42** [yargs/cliui#52]
It is difficult to tightly pack columns in cliui.  It has a tendency to want to expand columns to fill the output width.  Suppose I want the following output:
~~~
apple  one   red
banana two   green
cookie three blue
~~~

I might try this:
~~~js
var out = cliui().div(
  'apple\nbanana\ncookie\n', ' one\n two\n three\n', ' red\n green\n blue\n'
).toString()
~~~

But when column widths are not specified and the text is small enough, the columns divide the entire width nearly evenly:
~~~
apple                      one                       red
banana                     two                       green
cookie                     three                     blue
~~~

I might try using the domain-specific language:
~~~js
var out = cliui().div(
  'apple\nbanana\ncookie\n', ' one\n two\n three\n', ' red\n green\n blue\n'
).toString()
~~~

The DSL has a special case for packing the first column tightly, but it still distributes the remaining space evenly among the other columns:
~~~
apple  one                                  red
banana two                                  green
cookie three                                blue
~~~

As far as I can tell, the only way is to remove the padding and fully specify all column widths:
~~~js
var out = cliui().div(
  {text: 'apple\nbanana\ncookie\n', width: 7},
  {text: 'one\ntwo\nthree\n', width: 6},
  {text: 'red\ngreen\nblue\n', width: 5}
).toString()
~~~

But that seems to defeat the purpose.  One of the great things about cliui is that it can figure out the column widths for me.

There might be a trick that I'm missing.  If there isn't, one way to resolve this would be to have the DSL do its special case packing for all columns, not just the first.  Another way would be for columns in general to shrink to their longest row of content (after wrapping) when no width is specified (then the DSL wouldn't need its special case at all).  That may result in a drastic change in behavior though, so it may be worth guarding that change behind either a cliui option or a column option.

**Comment by bcoe** [comment]
@sbj42 as with the other issue, I apologize that I took so long to answer this issue; and I imagine you might have moved on from working with cliui.

However! if this is still a library you use, I would happily accept your help improving the library for your use-cases; as long as we're careful about making sure yargs' and nyc's output remains close to the same.

find me here: http://devtoolscommunity.herokuapp.com/

**Comment by sbj42** [comment]
No problem. The project I was working on that used `cliui` is on hold at the moment, so there is no urgency to this issue. I'll let you know if that changes.
